"""PME-grid electrostatic embedding helpers."""

import numpy as np

from pyqed.qchem.dft.grid import AOGrid


def pme_reciprocal_hcore(
    mol,
    mm_coords,
    mm_charges,
    cell,
    pbc=True,
    coulomb_constant=1.0,
    alpha=0.35,
    mesh=(16, 16, 16),
    grid=None,
):
    """Build the smooth reciprocal PME one-electron operator.

    The returned matrix is ``-<chi_mu|phi_MM^recip|chi_nu>`` in the AO basis,
    where ``phi_MM^recip`` is the reciprocal-space PME potential generated by
    the MM charges.  This is the long-range Hamiltonian building block; the
    force-consistent QM/MM PME coupling still needs matching derivatives.
    """
    if grid is None:
        grid = AOGrid.atom_centered(mol, with_grad=False)
    from pyqed.md.calculators import pme_reciprocal_potential

    potential = pme_reciprocal_potential(
        mm_coords,
        mm_charges,
        grid.coords,
        cell,
        pbc=pbc,
        coulomb_constant=coulomb_constant,
        alpha=alpha,
        mesh=mesh,
    )
    return pme_potential_hcore_from_grid(grid, potential)


def pme_potential_hcore_from_grid(grid, potential):
    """Contract a scalar electrostatic potential on an AO grid into hcore."""
    potential = np.asarray(potential, dtype=float)
    if potential.shape != grid.weights.shape:
        raise ValueError(
            f"potential has shape {potential.shape}, expected {grid.weights.shape}."
        )
    return -np.einsum(
        "g,gu,gv->uv",
        grid.weights * potential,
        grid.ao,
        grid.ao,
        optimize=True,
    )
