import numpy as np
import scipy.linalg as la
import time
from pyqed.qchem.gdvr.rhf import (
    SweepNewtonHelper, sweep_optimize_driver, 
    rebuild_Hcore_from_d, eri_JK_from_kernels_M1,
    CollocatedERIOp
)


# 1. DMRG Newton Helper
class DMRGNewtonHelper(SweepNewtonHelper):
    """
    A subclass of SweepNewtonHelper that implements the Exact Gradient and Hessian
    for the DMRG Energy Functional: E = Sum(P*h) + 0.5 * Sum(D*J).
    """
    def __init__(self, h1_nm, S_prim, eriop, D_spatial):
        super().__init__(h1_nm, S_prim, eriop)
        self.D_spatial = D_spatial # The Diagonal 2-RDM from DMRG

    def get_gradient_slice_onthefly(self, n, d_stack, P_slice):
        """
        Computes the gradient g_n for the DMRG functional.
        g_n = 2 * [ Sum_m P_nm * h_nm * d_m + Sum_k D_nk * J_k * d_n ]
        """
        Nz = self.Nz
        N  = self.N
        dn = d_stack[n]
        
        g_n = np.zeros(N, dtype=float)
        
        # --- 1. One-Electron Part (Hopping) ---
        # Sum_m P_nm * h_nm * d_m
        for m in range(Nz):
            p_nm = P_slice[n, m]
            if abs(p_nm) > 1e-12:
                # h1_nm[n, m] returns the operator matrix
                h_op = self.h1_nm[n, m]
                g_n += p_nm * (h_op @ d_stack[m])
                
        # --- 2. Two-Electron Part (Coulomb Correlation) ---
        # Sum_k D_nk * J_k * d_n
        # J_k is the potential generated by density |d_k|^2
        
        J_total = np.zeros((N, N), dtype=float)
        
        for k in range(Nz):
            d_nk = self.D_spatial[n, k]
            if abs(d_nk) > 1e-12:
                dk = d_stack[k]
                # block_nm__kl(n,n, k,k, dk, dk) returns the Matrix J_k
                J_k = self.eriop.block_nm__kl(n, n, k, k, dk, dk)
                
                # Handle sparse/diagonal return types from the library
                if J_k.ndim == 1:
                    J_total += d_nk * np.diag(J_k)
                else:
                    J_total += d_nk * J_k
                    
        # Apply Total Potential to d_n
        g_n += J_total @ dn
        
        # Scale by 2 for the derivative
        g_n *= 2.0
        
        return g_n

    def get_diagonal_hessian_block_sparse(self, n, d_stack, P_slice):
        """
        Computes the diagonal Hessian block H_nn.
        H_nn = 2 * [ P_nn * h_nn + Sum_k D_nk * J_k ]
        """
        N = self.N
        Nz = self.Nz
        
        # 1. One-Electron Hessian
        # P_nn * h_nn
        H_nn = P_slice[n, n] * self.h1_nm[n, n].copy()
        
        # 2. Two-Electron Hessian (Mean Field approximation)
        # Sum_k D_nk * J_k
        for k in range(Nz):
            d_nk = self.D_spatial[n, k]
            if abs(d_nk) > 1e-12:
                dk = d_stack[k]
                J_k = self.eriop.block_nm__kl(n, n, k, k, dk, dk)
                
                if J_k.ndim == 1:
                    H_nn += d_nk * np.diag(J_k)
                else:
                    H_nn += d_nk * J_k
                    
        H_nn *= 2.0
        return H_nn

def extract_rdms_for_helper(solver, n_spatial, sym_mgr=None, verbose=False):
    """
    Build spatial 1-RDM P[p,q] and a 'diagonal 2-RDM' D[p,q] needed by your AO Newton helper.
    Uses full make_rdm1() to capture exact off-diagonal hopping terms.
    """
    state = solver.ground_state
    
    # Get 1-RDM
    if sym_mgr is not None and hasattr(state.factors[0], 'qns'):
        P_spin = state.make_rdm1(sym_mgr=sym_mgr)
    elif hasattr(state.factors[0], 'qns'):
        from pyqed.mps.mps import symmetric_to_dense
        dense_state = symmetric_to_dense(state)
        P_spin = dense_state.make_rdm1()
    else:
        P_spin = state.make_rdm1()

    #  spin-sum to spatial 1-RDM 
    P_spatial = np.zeros((n_spatial, n_spatial), dtype=float)
    for p in range(n_spatial):
        for q in range(n_spatial):
            val = P_spin[2*p, 2*q] + P_spin[2*p+1, 2*q+1]
            P_spatial[p, q] = float(np.real(val))

    # Get Diagonal 2-RDM
    rdm2_dict = state.make_diagonal_rdm2()
    D_spatial = np.zeros((n_spatial, n_spatial), dtype=float)

    def get_nn(i, j):
        if i == j:
            return float(np.real(P_spin[i, i]))
        a, b = (i, j) if i < j else (j, i)
        return float(np.real(rdm2_dict.get((a, b), 0.0)))

    for p in range(n_spatial):
        for q in range(n_spatial):
            if p == q:
                # for same spatial orbital: <n_pα n_pβ>
                D_spatial[p, q] = 2.0 * get_nn(2*p, 2*p+1)
            else:
                val  = get_nn(2*p,   2*q)   + get_nn(2*p,   2*q+1)
                val += get_nn(2*p+1, 2*q)   + get_nn(2*p+1, 2*q+1)
                D_spatial[p, q] = val

    if verbose:
        print(f"[DMRG-SCF] Extracted RDM Tr(P)={np.trace(P_spatial):.4f}")
        # sanity: hermiticity
        anti = np.max(np.abs(P_spatial - P_spatial.T))
        print(f"[DMRG-SCF] max|P-P^T|={anti:.3e}")

    return P_spatial, D_spatial




# 3. Main ReOptimization for at AO level
def dmrg_ao_optimization_step(
    mol, d_stack, sym_mgr, S_prim, ERIop, h1_nm_func, 
    z, Kz, T_prim, alphas, centers, labels, K_h, Kx_h,
    solver, Enuc=0.0, n_cycles=5, ridge=0.5, verbose=True
):
    # 1. Extract RDMs
    P_spatial, D_spatial = extract_rdms_for_helper(solver, d_stack.shape[0], sym_mgr=sym_mgr, verbose=verbose)
    
    # 2. Instantiate the Custom Helper
    nh = DMRGNewtonHelper(h1_nm_func, S_prim, ERIop, D_spatial)
    
    # 3. Run Optimization using the ROBUST sweep_optimize_driver
    # This uses the Trust-Region KKT solver which prevents large energy spikes.
    d_new = sweep_optimize_driver(
        nh, 
        d_stack, 
        P_spatial, 
        S_prim,
        n_cycles=n_cycles,
        ridge=ridge,
        trust_step=1,
        trust_radius=1,
        verbose=verbose
    )
    
    return d_new
