"""Browser and notebook visualization helpers.

The public :func:`view` function builds a small, serializable scene rather
than tying Python to a particular JavaScript renderer.  Geometry-only scenes
retain the compact URL-fragment protocol used by older versions of the
viewer.  Volumetric scenes are sent with ``postMessage`` from a local launcher
so potentially large orbital and density arrays never appear in a URL.
"""

from __future__ import annotations

import base64
from dataclasses import dataclass, field
from html import escape
import json
from pathlib import Path
import re
import tempfile
from types import MappingProxyType
from typing import Any, Iterable, Mapping
from urllib.parse import urlencode, urlsplit
import webbrowser

import numpy as np

from pyqed.units import au2angstrom, au2wavenumber


_VIEWER_URL = "https://pyqed.org/viewer"
_VIEWER_ORIGIN = "https://pyqed.org"
_SCENE_KIND = "pyqed-scene"
_SCENE_VERSION = 1
_MAX_ATOMS = 500
_MAX_FIELDS = 512
_MAX_AXIS_SIZE = 2048
_MAX_FIELD_POINTS = 2_000_000
_MAX_SCENE_POINTS = 8_000_000
_MAX_SERIALIZED_BYTES = 64_000_000
_MAX_CUBE_BYTES = 80_000_000
_MAX_GEOMETRY_CHARS = 1_000_000
_MAX_FLOAT32 = float(np.finfo(np.float32).max)
_COLOR_PATTERN = re.compile(
    r"^(?:#[0-9a-f]{3}|#[0-9a-f]{6}|#[0-9a-f]{8}|[a-z][a-z0-9_-]{0,31})$",
    re.IGNORECASE,
)
_SIGNED_FIELD_KINDS = {
    "orbital",
    "spin-density",
    "difference-density",
    "transition-density",
    "esp",
    "generic",
}
_FIELD_KINDS = _SIGNED_FIELD_KINDS | {"electron-density"}
_REPRESENTATIONS = {
    "ball-stick": "ball-stick",
    "ball_and_stick": "ball-stick",
    "ball-and-stick": "ball-stick",
    "space-fill": "space-fill",
    "space_filling": "space-fill",
    "space-filling": "space-fill",
    "wireframe": "wireframe",
}
def _normalize_representation(value: str) -> str:
    try:
        return _REPRESENTATIONS[str(value).lower()]
    except KeyError as exc:
        choices = "ball-stick, space-fill, or wireframe"
        raise ValueError(f"representation must be {choices}") from exc


def _atom_symbols(molecule) -> list[str]:
    method = getattr(molecule, "atom_symbols", None)
    if callable(method):
        return list(method())
    natom = getattr(molecule, "natom", getattr(molecule, "natm", None))
    atom_symbol = getattr(molecule, "atom_symbol", None)
    if natom is not None and callable(atom_symbol):
        return [atom_symbol(i) for i in range(int(natom))]
    raise TypeError("molecule must provide atom_symbols() or atom_symbol(index)")


def _molecule_xyz(molecule, *, coordinates_unit: str) -> str:
    try:
        symbols = _atom_symbols(molecule)
        coordinates = np.asarray(molecule.atom_coords(), dtype=float)
    except AttributeError as exc:
        raise TypeError(
            "view() expects a molecule or an object with a .mol reference"
        ) from exc

    if coordinates.shape != (len(symbols), 3):
        raise ValueError(
            "atom_coords() must return an array with shape (number of atoms, 3)"
        )
    if not symbols:
        raise ValueError("cannot view a molecule with no atoms")
    if len(symbols) > _MAX_ATOMS:
        raise ValueError(f"the viewer supports at most {_MAX_ATOMS} atoms")
    if not np.all(np.isfinite(coordinates)):
        raise ValueError("molecular coordinates must be finite")

    unit = str(coordinates_unit).lower()
    if unit in {"bohr", "b", "au", "a.u."}:
        coordinates = coordinates * au2angstrom
    elif unit not in {"angstrom", "angstroms", "a", "å"}:
        raise ValueError("coordinates_unit must be 'bohr' or 'angstrom'")

    rows = [str(len(symbols)), "Generated by PyQED, coordinates in angstrom"]
    for symbol, (x, y, z) in zip(symbols, coordinates):
        symbol = str(symbol).strip()
        symbol = symbol[:1].upper() + symbol[1:].lower()
        if symbol not in _ELEMENT_SET:
            raise ValueError(f"invalid atomic symbol: {symbol!r}")
        if np.max(np.abs((x, y, z))) > _MAX_FLOAT32:
            raise ValueError("molecular coordinates exceed the viewer's numeric range")
        rows.append(f"{symbol:<3} {x: .10f} {y: .10f} {z: .10f}")
    return "\n".join(rows)


def _validate_xyz_payload(xyz: str) -> str:
    if not isinstance(xyz, str):
        raise TypeError("xyz must be text")
    if not xyz.strip():
        raise ValueError("xyz cannot be empty")
    if len(xyz) > _MAX_GEOMETRY_CHARS:
        raise ValueError("xyz must be smaller than 1 MB")

    raw_lines = [line.strip() for line in xyz.strip().splitlines()]
    first_is_count = bool(raw_lines and raw_lines[0].isdigit())
    if first_is_count:
        expected = int(raw_lines[0])
        coordinate_lines = raw_lines[2:]
    else:
        expected = None
        coordinate_lines = [
            row.strip()
            for line in raw_lines
            for row in line.split(";")
            if row.strip()
        ]

    atoms = 0
    for line in coordinate_lines:
        if not line:
            continue
        fields = re.split(r"[\s,]+", line)
        if len(fields) != 4:
            raise ValueError("each XYZ row must contain an element and three coordinates")
        symbol = fields[0][:1].upper() + fields[0][1:].lower()
        if symbol not in _ELEMENT_SET:
            raise ValueError(f"invalid atomic symbol: {fields[0]!r}")
        try:
            coordinates = [float(value.replace("D", "E").replace("d", "e")) for value in fields[1:]]
        except ValueError as exc:
            raise ValueError("XYZ coordinates must be numeric") from exc
        if not all(np.isfinite(value) and abs(value) <= _MAX_FLOAT32 for value in coordinates):
            raise ValueError("XYZ coordinates exceed the viewer's numeric range")
        atoms += 1

    if atoms == 0:
        raise ValueError("xyz must contain at least one atom")
    if atoms > _MAX_ATOMS:
        raise ValueError(f"the viewer supports at most {_MAX_ATOMS} atoms")
    if expected is not None and expected != atoms:
        raise ValueError(f"XYZ header declares {expected} atoms, but {atoms} were found")
    return xyz


def _xyz_from_arrays(symbols, coordinates_angstrom) -> str:
    class _ArrayMolecule:
        def atom_symbols(self):
            return symbols

        def atom_coords(self):
            return coordinates_angstrom

    return _molecule_xyz(_ArrayMolecule(), coordinates_unit="angstrom")


def _in_notebook() -> bool:
    try:
        from IPython import get_ipython
    except ImportError:
        return False
    shell = get_ipython()
    return shell is not None and getattr(shell, "kernel", None) is not None


def _real_array(values, *, name: str) -> np.ndarray:
    array = np.asarray(values)
    if np.iscomplexobj(array):
        real = np.real_if_close(array, tol=1000)
        if np.iscomplexobj(real):
            scale = max(1.0, float(np.max(np.abs(array.real))))
            if float(np.max(np.abs(array.imag))) > 1.0e-10 * scale:
                raise ValueError(f"{name} must be real for scalar-field visualization")
        array = np.asarray(real.real)
    try:
        array = np.array(array, dtype=float, copy=True)
    except (TypeError, ValueError) as exc:
        raise TypeError(f"{name} must contain numeric values") from exc
    if not np.all(np.isfinite(array)):
        raise ValueError(f"{name} must contain only finite values")
    return array


def _auto_isovalues(values: np.ndarray, kind: str) -> tuple[float, ...]:
    magnitudes = np.abs(values[np.nonzero(values)])
    if magnitudes.size == 0:
        return (1.0,)
    if kind == "electron-density":
        level = min(0.05, 0.10 * float(np.max(magnitudes)))
    else:
        level = 0.15 * float(np.percentile(magnitudes, 95.0))
    level = max(level, np.finfo(float).eps)
    return (level,)


def _normalize_isovalues(values, field_values, kind) -> tuple[float, ...]:
    if values is None:
        return _auto_isovalues(field_values, kind)
    if np.isscalar(values):
        result = (float(values),)
    else:
        result = tuple(float(value) for value in values)
    if not result or len(result) > 8:
        raise ValueError("isovalues must contain between one and eight values")
    if not all(
        np.isfinite(value) and 0.0 < value <= _MAX_FLOAT32 for value in result
    ):
        raise ValueError("isovalues must be positive finite 32-bit values")
    return result


def _same_grid_numbers(left, right) -> bool:
    left_values = np.concatenate((left.origin, left.axes.ravel()))
    right_values = np.concatenate((right.origin, right.axes.ravel()))
    return bool(
        np.all(
            np.abs(left_values - right_values)
            <= 1.0e-9 * np.maximum(1.0, np.abs(left_values))
        )
    )


def _validate_metadata(value: Mapping[str, Any]) -> dict[str, Any]:
    budget = [0]

    def clean(item, *, depth: int, context: str):
        budget[0] += 1
        if budget[0] > 512:
            raise ValueError("field metadata contains too many entries")
        if depth > 5:
            raise ValueError("field metadata is nested too deeply")
        if item is None or isinstance(item, (bool, str, int, float)):
            if isinstance(item, str) and len(item) > 1_000:
                raise ValueError("field metadata contains text longer than 1,000 characters")
            if isinstance(item, (int, float)) and not isinstance(item, bool):
                if not np.isfinite(item):
                    raise ValueError("field metadata contains a non-finite number")
            return item
        if isinstance(item, (list, tuple)):
            if len(item) > 128:
                raise ValueError("field metadata contains an array longer than 128 entries")
            return [
                clean(entry, depth=depth + 1, context=f"{context}[{index}]")
                for index, entry in enumerate(item)
            ]
        if isinstance(item, Mapping):
            result = {}
            for key, entry in item.items():
                if not isinstance(key, str) or not key or len(key) > 80 or key in {
                    "__proto__",
                    "constructor",
                    "prototype",
                }:
                    raise ValueError("field metadata contains an unsafe or overlong key")
                result[key] = clean(
                    entry,
                    depth=depth + 1,
                    context=f"{context}.{key}",
                )
            return result
        raise TypeError(f"{context} must contain JSON-compatible values only")

    return clean(dict(value), depth=0, context="field metadata")


def _freeze_metadata(value):
    if isinstance(value, dict):
        return MappingProxyType(
            {key: _freeze_metadata(entry) for key, entry in value.items()}
        )
    if isinstance(value, list):
        return tuple(_freeze_metadata(entry) for entry in value)
    return value


def _metadata_payload(value):
    if isinstance(value, Mapping):
        return {key: _metadata_payload(entry) for key, entry in value.items()}
    if isinstance(value, tuple):
        return [_metadata_payload(entry) for entry in value]
    return value


@dataclass(frozen=True)
class ScalarField3D:
    """A scalar field sampled on a regular, possibly skewed, 3-D grid.

    ``origin`` and the rows of ``axes`` are expressed in Angstrom.  Values are
    flattened in C order only when serialized; the Python object retains its
    natural ``(nx, ny, nz)`` array.
    """

    name: str
    values: np.ndarray
    origin: tuple[float, float, float] | np.ndarray
    axes: tuple[tuple[float, float, float], ...] | np.ndarray
    kind: str = "generic"
    label: str | None = None
    isovalues: tuple[float, ...] | float | None = None
    colors: tuple[str, ...] | None = None
    opacity: float = 0.72
    units: str | None = None
    surface_field: str | None = None
    metadata: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        name = str(self.name).strip()
        if not name:
            raise ValueError("field name cannot be empty")
        if len(name) > 80 or any(ord(character) < 32 or ord(character) == 127 for character in name):
            raise ValueError("field name must fit on one line and contain at most 80 characters")
        values = _real_array(self.values, name=f"field {name!r}")
        if values.ndim != 3 or any(size < 2 for size in values.shape):
            raise ValueError("field values must have shape (nx, ny, nz) with each size >= 2")
        if any(size > _MAX_AXIS_SIZE for size in values.shape):
            raise ValueError(f"each field grid dimension must be at most {_MAX_AXIS_SIZE}")
        if values.size > _MAX_FIELD_POINTS:
            raise ValueError(
                f"field {name!r} has {values.size:,} points; limit is {_MAX_FIELD_POINTS:,}"
            )
        origin = _real_array(self.origin, name="field origin")
        axes = _real_array(self.axes, name="field axes")
        if origin.shape != (3,):
            raise ValueError("field origin must have shape (3,)")
        if axes.shape != (3, 3):
            raise ValueError("field axes must have shape (3, 3)")
        if any(
            np.max(np.abs(array), initial=0.0) > _MAX_FLOAT32
            for array in (values, origin, axes)
        ):
            raise ValueError("field values and grid coordinates must fit in float32")
        if abs(float(np.linalg.det(axes))) < 1.0e-15:
            raise ValueError("field grid axes must be linearly independent")
        kind = str(self.kind).lower()
        if kind not in _FIELD_KINDS:
            choices = ", ".join(sorted(_FIELD_KINDS))
            raise ValueError(f"field kind must be one of: {choices}")
        opacity = float(self.opacity)
        if not 0.0 < opacity <= 1.0:
            raise ValueError("field opacity must lie in (0, 1]")
        colors = self.colors
        if colors is None:
            colors = (
                ("#2563eb", "#dc2626")
                if kind in _SIGNED_FIELD_KINDS
                else ("#2563eb",)
            )
        colors = tuple(str(color) for color in colors)
        if not 1 <= len(colors) <= 2 or any(
            _COLOR_PATTERN.fullmatch(color) is None for color in colors
        ):
            raise ValueError("field colors must contain one or two named or hexadecimal colors")
        label = name if self.label is None else str(self.label).strip()
        if not label or len(label) > 120 or any(
            ord(character) < 32 or ord(character) == 127 for character in label
        ):
            raise ValueError("field label must fit on one line and contain at most 120 characters")
        units = None if self.units is None else str(self.units).strip()
        if units is not None and (
            not units
            or len(units) > 40
            or any(ord(character) < 32 or ord(character) == 127 for character in units)
        ):
            raise ValueError("field units must fit on one line and contain at most 40 characters")
        surface_field = None if self.surface_field is None else str(self.surface_field).strip()
        if surface_field is not None and (
            not surface_field
            or len(surface_field) > 80
            or any(ord(character) < 32 or ord(character) == 127 for character in surface_field)
        ):
            raise ValueError(
                "surface_field must fit on one line and contain at most 80 characters"
            )
        metadata = _validate_metadata(self.metadata)

        # The browser renderer consumes float32 volumes. Store that exact
        # representation here so large all-state scenes do not keep a second
        # float64 copy in Python.
        values = np.array(values, dtype=np.float32, copy=True)
        values.setflags(write=False)
        origin.setflags(write=False)
        axes.setflags(write=False)
        object.__setattr__(self, "name", name)
        object.__setattr__(self, "values", values)
        object.__setattr__(self, "origin", origin)
        object.__setattr__(self, "axes", axes)
        object.__setattr__(self, "kind", kind)
        object.__setattr__(self, "label", label)
        object.__setattr__(self, "isovalues", _normalize_isovalues(self.isovalues, values, kind))
        object.__setattr__(self, "colors", colors)
        object.__setattr__(self, "opacity", opacity)
        object.__setattr__(self, "units", units)
        object.__setattr__(self, "surface_field", surface_field)
        object.__setattr__(self, "metadata", _freeze_metadata(metadata))

    @property
    def shape(self) -> tuple[int, int, int]:
        return tuple(int(size) for size in self.values.shape)

    def to_payload(self) -> dict[str, Any]:
        encoded_values = base64.b64encode(
            np.asarray(self.values, dtype="<f4").ravel(order="C").tobytes()
        ).decode("ascii")
        payload: dict[str, Any] = {
            "name": self.name,
            "label": self.label,
            "kind": self.kind,
            "shape": list(self.shape),
            "origin": self.origin.tolist(),
            "axes": self.axes.tolist(),
            "values": encoded_values,
            "value_encoding": "float32-le-base64",
            "isovalues": list(self.isovalues),
            "colors": list(self.colors),
            "opacity": self.opacity,
        }
        if self.units is not None:
            payload["units"] = self.units
        if self.surface_field is not None:
            payload["surface_field"] = self.surface_field
        if self.metadata:
            payload["metadata"] = _metadata_payload(self.metadata)
        return payload


def _viewer_origin(viewer_url: str) -> str:
    parts = urlsplit(viewer_url)
    if parts.scheme != "https" or not parts.netloc or parts.username or parts.password:
        raise ValueError("viewer_url must be an HTTPS URL")
    origin = f"{parts.scheme}://{parts.netloc}"
    if origin != _VIEWER_ORIGIN:
        raise ValueError(f"viewer_url must use the trusted origin {_VIEWER_ORIGIN}")
    return origin


@dataclass(frozen=True)
class NormalModeAnimation:
    """Browser-ready displacement data for one harmonic normal mode."""

    mode_index: int
    frequency_cm1: float
    displacements: np.ndarray
    amplitude_angstrom: float
    frames: int = 24
    interval: int = 30

    def __post_init__(self) -> None:
        mode_index = int(self.mode_index)
        frequency = float(self.frequency_cm1)
        displacements = np.array(self.displacements, dtype=float, copy=True)
        amplitude = float(self.amplitude_angstrom)
        frames = int(self.frames)
        interval = int(self.interval)
        if mode_index < 0:
            raise ValueError("mode_index must be non-negative")
        if not np.isfinite(frequency):
            raise ValueError("frequency_cm1 must be finite")
        if displacements.ndim != 2 or displacements.shape[1] != 3:
            raise ValueError("normal-mode displacements must have shape (natom, 3)")
        if not np.all(np.isfinite(displacements)):
            raise ValueError("normal-mode displacements must be finite")
        if not np.isfinite(amplitude) or amplitude <= 0.0 or amplitude > 10.0:
            raise ValueError("amplitude_angstrom must be in the interval (0, 10]")
        if frames < 8 or frames > 120:
            raise ValueError("frames must be between 8 and 120")
        if interval < 16 or interval > 1000:
            raise ValueError("interval must be between 16 and 1000 milliseconds")
        displacements.setflags(write=False)
        object.__setattr__(self, "mode_index", mode_index)
        object.__setattr__(self, "frequency_cm1", frequency)
        object.__setattr__(self, "displacements", displacements)
        object.__setattr__(self, "amplitude_angstrom", amplitude)
        object.__setattr__(self, "frames", frames)
        object.__setattr__(self, "interval", interval)

    @property
    def label(self) -> str:
        return f"Mode {self.mode_index}: {self.frequency_cm1:.1f} cm^-1"

    def to_payload(self) -> dict[str, Any]:
        return {
            "mode_index": self.mode_index,
            "frequency_cm1": self.frequency_cm1,
            "displacements": self.displacements.tolist(),
            "amplitude_angstrom": self.amplitude_angstrom,
            "frames": self.frames,
            "interval": self.interval,
        }


@dataclass
class SceneView:
    """A geometry and zero or more regular scalar fields for the web viewer."""

    xyz: str | None = None
    fields: tuple[ScalarField3D, ...] = ()
    representation: str = "ball-stick"
    labels: bool = False
    width: int = 900
    height: int = 640
    title: str | None = None
    active_field: str | int | None = None
    vibration: NormalModeAnimation | None = None
    viewer_url: str = _VIEWER_URL

    def __post_init__(self) -> None:
        self.representation = _normalize_representation(self.representation)
        self.width = int(self.width)
        self.height = int(self.height)
        if self.width < 240 or self.height < 240:
            raise ValueError("width and height must each be at least 240 pixels")
        _viewer_origin(self.viewer_url)
        self.fields = tuple(self.fields)
        if any(not isinstance(item, ScalarField3D) for item in self.fields):
            raise TypeError("fields must contain ScalarField3D objects")
        if len(self.fields) > _MAX_FIELDS:
            raise ValueError(f"a scene can contain at most {_MAX_FIELDS} fields")
        if sum(item.values.size for item in self.fields) > _MAX_SCENE_POINTS:
            raise ValueError(f"scene exceeds the {_MAX_SCENE_POINTS:,}-point limit")
        names = [item.name for item in self.fields]
        if len(names) != len(set(names)):
            raise ValueError("field names must be unique within a scene")
        for item in self.fields:
            if item.surface_field is not None:
                if item.kind != "esp":
                    raise ValueError("only an ESP field may reference surface_field")
                if item.surface_field not in names:
                    raise ValueError(
                        f"field {item.name!r} references missing surface field "
                        f"{item.surface_field!r}"
                    )
                surface = self.fields[names.index(item.surface_field)]
                if surface.kind != "electron-density":
                    raise ValueError("surface_field must reference an electron-density field")
                if (
                    item.shape != surface.shape
                    or not _same_grid_numbers(item, surface)
                ):
                    raise ValueError("ESP and surface fields must use identical grids")
        if self.active_field is not None:
            if isinstance(self.active_field, str):
                if self.active_field not in names:
                    raise ValueError(f"active_field {self.active_field!r} is not in the scene")
            else:
                if isinstance(self.active_field, (bool, np.bool_)):
                    raise TypeError("active_field must be a field name or integer index")
                index = int(self.active_field)
                if index < 0 or index >= len(self.fields):
                    raise IndexError("active_field index is out of range")
                self.active_field = index
        elif self.fields:
            self.active_field = self.fields[0].name
        if self.xyz is None and not self.fields:
            raise ValueError("a scene must contain geometry or at least one scalar field")
        if self.xyz is not None:
            self.xyz = _validate_xyz_payload(self.xyz)
        if self.vibration is not None:
            if not isinstance(self.vibration, NormalModeAnimation):
                raise TypeError("vibration must be a NormalModeAnimation")
            if self.xyz is None:
                raise ValueError("normal-mode animation requires molecular geometry")
        if self.title is not None:
            self.title = str(self.title).strip()
            if not self.title or len(self.title) > 160 or any(
                ord(character) < 32 or ord(character) == 127
                for character in self.title
            ):
                raise ValueError("title must fit on one line and contain at most 160 characters")

    @property
    def url(self) -> str:
        """Return the direct viewer URL.

        Only geometry-only scenes use the legacy fragment.  Volumetric data is
        deliberately absent from this property and is transported by
        :meth:`open` or :meth:`_repr_html_` using ``postMessage``.
        """
        if self.fields or self.vibration is not None:
            return self.viewer_url
        fragment = urlencode(
            {
                "xyz": self.xyz,
                "representation": self.representation,
                "labels": "1" if self.labels else "0",
            }
        )
        return f"{self.viewer_url}#{fragment}"

    def payload(self) -> dict[str, Any]:
        scene: dict[str, Any] = {
            "version": _SCENE_VERSION,
            "kind": _SCENE_KIND,
            "molecule": None
            if self.xyz is None
            else {
                "xyz": self.xyz,
                "representation": self.representation,
                "labels": bool(self.labels),
            },
            "fields": [item.to_payload() for item in self.fields],
            "active_field": self.active_field,
        }
        if self.vibration is not None:
            scene["vibration"] = self.vibration.to_payload()
        if self.title:
            scene["title"] = self.title
        return scene

    def _encoded_payload(self) -> str:
        raw = json.dumps(
            self.payload(),
            ensure_ascii=True,
            separators=(",", ":"),
            allow_nan=False,
        ).encode("utf-8")
        if len(raw) > _MAX_SERIALIZED_BYTES:
            raise ValueError(
                f"serialized scene is {len(raw):,} bytes; limit is "
                f"{_MAX_SERIALIZED_BYTES:,}"
            )
        return base64.b64encode(raw).decode("ascii")

    def _launcher_html(self, *, full_page: bool) -> str:
        payload = self._encoded_payload()
        src = escape(self.viewer_url, quote=True)
        style = (
            "position:fixed;inset:0;width:100%;height:100%;border:0"
            if full_page
            else "width:100%;max-width:100%;border:1px solid #294452"
        )
        outer = (
            "<!doctype html><html><head><meta charset='utf-8'>"
            "<title>PyQED Viewer</title></head><body style='margin:0'>"
            if full_page
            else ""
        )
        closing = "</body></html>" if full_page else ""
        # The scene is base64 rather than raw JSON so labels cannot terminate
        # the script element.  targetOrigin is intentionally a fixed literal.
        return (
            f"{outer}<iframe id='pyqed-scene-viewer' src='{src}' "
            f"title='PyQED scientific viewer' width='{self.width}' "
            f"height='{self.height}' style='{style}' loading='eager' "
            "referrerpolicy='no-referrer' "
            "sandbox='allow-scripts allow-same-origin allow-downloads'></iframe>"
            "<script>(function(){'use strict';"
            f"const scene=JSON.parse(atob('{payload}'));"
            "const frame=document.getElementById('pyqed-scene-viewer');"
            "let ready=false;const timers=[];"
            "const send=()=>frame.contentWindow.postMessage("
            "{type:'pyqed:scene',scene:scene},'https://pyqed.org');"
            "window.addEventListener('message',(event)=>{"
            "if(event.source!==frame.contentWindow||event.origin!=='https://pyqed.org'"
            "||!event.data||event.data.type!=='pyqed:viewer-ready')return;"
            "ready=true;timers.forEach(clearTimeout);send();});"
            "frame.addEventListener('load',()=>{[500,1500,3500].forEach((delay)=>{"
            "timers.push(setTimeout(()=>{if(!ready)send();},delay));});});"
            "})();</script>"
            f"{closing}"
        )

    def open(self) -> bool:
        """Open the scene in the default browser."""
        if not self.fields and self.vibration is None:
            return webbrowser.open_new_tab(self.url)
        handle = tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            suffix=".html",
            prefix="pyqed-view-",
            delete=False,
        )
        path = Path(handle.name)
        try:
            with handle:
                handle.write(self._launcher_html(full_page=True))
        except Exception:
            path.unlink(missing_ok=True)
            raise
        # Keep the launcher after this Python process exits. A short script can
        # otherwise delete it before the browser has finished loading it; the
        # operating system will eventually clean its temporary directory.
        return webbrowser.open_new_tab(path.resolve().as_uri())

    def _repr_html_(self) -> str:
        """Render the interactive viewer inline in a Jupyter frontend."""
        if self.fields or self.vibration is not None:
            return self._launcher_html(full_page=False)
        src = escape(self.url, quote=True)
        return (
            f'<iframe src="{src}" title="PyQED molecular viewer" '
            f'width="{self.width}" height="{self.height}" '
            'style="width:100%;max-width:100%;border:1px solid #294452;" '
            'loading="lazy" referrerpolicy="no-referrer" '
            'sandbox="allow-scripts allow-same-origin allow-downloads"></iframe>'
        )


class VolumeView(SceneView):
    """A :class:`SceneView` containing one or more scalar fields."""


# Compatibility name: geometry and fields now use the same generic scene.
MoleculeView = SceneView


def _molecule_from_object(obj):
    if callable(getattr(obj, "atom_coords", None)):
        return obj
    for attribute in ("mol", "molecule"):
        candidate = getattr(obj, attribute, None)
        if candidate is not None and callable(getattr(candidate, "atom_coords", None)):
            return candidate
    for attribute in ("_scf", "mf", "base"):
        reference = getattr(obj, attribute, None)
        candidate = getattr(reference, "mol", None)
        if candidate is not None and callable(getattr(candidate, "atom_coords", None)):
            return candidate
    raise TypeError("could not find molecular geometry on the supplied object")


def _normal_mode_animation(
    hessian,
    molecule,
    *,
    mode,
    amplitude,
    coordinates_unit,
    frames,
    interval,
) -> NormalModeAnimation:
    analysis_method = getattr(hessian, "vibrational_analysis", None)
    if not callable(analysis_method):
        raise TypeError("mode viewing requires a completed Hessian object")
    try:
        analysis = analysis_method()
    except ValueError as exc:
        raise ValueError(
            "run the Hessian calculation before calling view(hessian, mode=...)"
        ) from exc
    if not isinstance(analysis, Mapping):
        raise TypeError("vibrational_analysis() must return a mapping")

    raw_modes = analysis.get("modes", analysis.get("norm_mode"))
    if raw_modes is None:
        raise ValueError("vibrational analysis did not return normal modes")
    modes = np.asarray(raw_modes, dtype=float)
    if modes.ndim != 3 or modes.shape[2] != 3:
        raise ValueError("normal modes must have shape (nmodes, natom, 3)")
    if isinstance(mode, (bool, np.bool_)):
        raise TypeError("mode must be an integer index")
    mode_index = int(mode)
    if mode_index != mode:
        raise TypeError("mode must be an integer index")
    if mode_index < 0 or mode_index >= modes.shape[0]:
        raise IndexError(f"mode index {mode_index} is outside [0, {modes.shape[0]})")

    coordinates = np.asarray(molecule.atom_coords(), dtype=float)
    displacement = np.asarray(modes[mode_index], dtype=float)
    if displacement.shape != coordinates.shape:
        raise ValueError("normal-mode shape does not match the molecule")
    if not np.all(np.isfinite(displacement)):
        raise ValueError("normal-mode displacements must be finite")
    maximum = float(np.max(np.linalg.norm(displacement, axis=1)))
    if maximum <= np.finfo(float).eps:
        raise ValueError("selected normal mode has zero displacement")

    unit = str(coordinates_unit).lower()
    if unit in {"bohr", "b", "au", "a.u."}:
        coordinates_angstrom = coordinates * au2angstrom
    elif unit in {"angstrom", "angstroms", "a", "å"}:
        coordinates_angstrom = coordinates
    else:
        raise ValueError("coordinates_unit must be 'bohr' or 'angstrom'")
    if amplitude == "auto":
        span = float(np.max(np.ptp(coordinates_angstrom, axis=0)))
        amplitude_angstrom = min(0.5, max(0.12, 0.18 * max(span, 1.0)))
    else:
        amplitude_angstrom = float(amplitude)
        if (
            not np.isfinite(amplitude_angstrom)
            or amplitude_angstrom <= 0.0
            or amplitude_angstrom > 10.0
        ):
            raise ValueError("amplitude must be 'auto' or a value in (0, 10] angstrom")
    displacement_angstrom = displacement * (amplitude_angstrom / maximum)

    if "freq_cm1" in analysis:
        frequencies = analysis["freq_cm1"]
    elif "freq_wavenumber" in analysis:
        frequencies = analysis["freq_wavenumber"]
    elif "freq_au" in analysis:
        frequencies = np.asarray(analysis["freq_au"]) * au2wavenumber
    else:
        raise ValueError("vibrational analysis did not return frequencies")
    frequencies = np.asarray(frequencies)
    if frequencies.shape != (modes.shape[0],):
        raise ValueError("vibrational frequencies do not match the normal modes")
    frequency = np.real_if_close(frequencies[mode_index])
    if np.iscomplexobj(frequency):
        frequency = frequency.real - abs(frequency.imag)

    return NormalModeAnimation(
        mode_index=mode_index,
        frequency_cm1=float(frequency),
        displacements=displacement_angstrom,
        amplitude_angstrom=amplitude_angstrom,
        frames=frames,
        interval=interval,
    )


def _scf_reference(obj):
    if getattr(obj, "mo_coeff", None) is not None and getattr(obj, "mo_occ", None) is not None:
        return obj
    for attribute in ("_scf", "mf", "base"):
        reference = getattr(obj, attribute, None)
        if (
            reference is not None
            and getattr(reference, "mo_coeff", None) is not None
            and getattr(reference, "mo_occ", None) is not None
        ):
            return reference
    casci = getattr(obj, "casci", getattr(obj, "solver", None))
    reference = getattr(casci, "mf", None)
    if reference is not None and getattr(reference, "mo_coeff", None) is not None:
        return reference
    return None


def _grid(molecule, *, nx, ny, nz, margin, bounds):
    from pyqed.qchem.tools.cubegen import Cube

    return Cube(
        molecule,
        nx=int(nx),
        ny=None if ny is None else int(ny),
        nz=None if nz is None else int(nz),
        margin=float(margin),
        bounds=bounds,
    )


def _evaluate_ao(reference, points) -> np.ndarray:
    molecule = reference.mol
    eval_gto = getattr(molecule, "eval_gto", None)
    if callable(eval_gto):
        name = "GTOval_cart" if bool(getattr(molecule, "cart", False)) else "GTOval_sph"
        values = np.asarray(eval_gto(name, points))
        if values.ndim != 2:
            raise ValueError("molecule.eval_gto() did not return a 2-D AO array")
        return values.T

    analysis = None
    if callable(getattr(reference, "analyze", None)):
        try:
            candidate = reference.analyze()
        except TypeError:
            candidate = None
        if callable(getattr(candidate, "_evaluate_ao_values", None)):
            analysis = candidate
    if analysis is None:
        from pyqed.qchem.hf.analysis import RHFAnalysis

        analysis = RHFAnalysis(reference)
    return np.asarray(
        analysis._evaluate_ao_values(points, screen_basis=True, tol_screen=1.0e-8)
    )


def _grid_geometry(cube) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    origin_bohr = np.asarray(cube.origin, dtype=float)
    axes_bohr = np.diag(np.asarray(cube.spacing, dtype=float))
    return cube.get_coords(), origin_bohr * au2angstrom, axes_bohr * au2angstrom


def _spin_arrays(reference, attribute: str) -> tuple[np.ndarray, ...]:
    value = getattr(reference, attribute, None)
    if value is None:
        raise ValueError(f"SCF object has no {attribute}; run the calculation first")
    if isinstance(value, (tuple, list)) and len(value) == 2:
        return tuple(np.asarray(item) for item in value)
    array = np.asarray(value)
    if array.ndim >= 2 and array.shape[0] == 2 and attribute != "mo_coeff":
        return (array[0], array[1])
    if attribute == "mo_coeff" and array.ndim == 3 and array.shape[0] == 2:
        return (array[0], array[1])
    return (array,)


def _frontier_index(occupations, selector: str) -> int:
    occ = np.asarray(occupations, dtype=float)
    occupied = np.flatnonzero(occ > 1.0e-8)
    virtual = np.flatnonzero(occ <= 1.0e-8)
    key = selector.strip().lower().replace("_", "").replace(" ", "")
    if key.startswith("homo"):
        if occupied.size == 0:
            raise ValueError("HOMO requires at least one occupied orbital")
        base = int(occupied[-1])
        suffix = key[4:]
    elif key.startswith("lumo"):
        if virtual.size == 0:
            raise ValueError("LUMO requires at least one virtual orbital")
        base = int(virtual[0])
        suffix = key[4:]
    else:
        raise ValueError(f"unknown orbital selector {selector!r}")
    if suffix:
        try:
            base += int(suffix)
        except ValueError as exc:
            raise ValueError(f"invalid frontier-orbital offset in {selector!r}") from exc
    return base


def _orbital_indices(selector, occupations, nmo: int) -> list[tuple[int, str]]:
    if isinstance(selector, str):
        key = selector.strip().lower()
        if key == "all":
            requested = list(range(nmo))
        else:
            requested = [selector]
    elif np.isscalar(selector):
        requested = [selector]
    else:
        requested = list(selector)
        if not requested:
            raise ValueError("orbital selector list cannot be empty")

    result = []
    for item in requested:
        if isinstance(item, str):
            index = _frontier_index(occupations, item)
            label = item.strip().upper()
        else:
            if isinstance(item, (bool, np.bool_)):
                raise TypeError("boolean values are not orbital indices")
            index = int(item)
            if index != item:
                raise TypeError("orbital indices must be integers")
            label = f"MO {index + 1}"
        if index < 0 or index >= nmo:
            raise IndexError(f"orbital index {index} is outside [0, {nmo})")
        result.append((index, label))
    return result


def _field_values(coeff, ao_values, shape, *, name):
    if coeff.shape != (ao_values.shape[0],):
        raise ValueError(
            f"{name} coefficient length {coeff.shape[0]} does not match AO dimension "
            f"{ao_values.shape[0]}"
        )
    return _real_array(coeff.conj() @ ao_values, name=name).reshape(shape)


def _orbital_fields(
    reference,
    selector,
    *,
    coeff,
    orbital_spin,
    ao_values,
    shape,
    origin,
    axes,
    isovalues,
    opacity,
) -> list[ScalarField3D]:
    coefficients = _spin_arrays(reference, "mo_coeff")
    occupations = _spin_arrays(reference, "mo_occ")
    energies = _spin_arrays(reference, "mo_energy") if getattr(reference, "mo_energy", None) is not None else ()

    if coeff is not None and selector is not None:
        raise ValueError("provide orbital selectors or coeff, not both")
    custom = coeff
    if custom is None and isinstance(selector, np.ndarray) and selector.ndim in (1, 2):
        custom = selector
        selector = None
    if custom is not None:
        custom = np.asarray(custom)
        if custom.ndim == 1:
            custom = custom[:, None]
        if custom.ndim != 2:
            raise ValueError("custom orbital coefficients must be a 1-D vector or 2-D column matrix")
        result = []
        for column in range(custom.shape[1]):
            name = "custom-orbital" if custom.shape[1] == 1 else f"custom-orbital-{column + 1}"
            values = _field_values(custom[:, column], ao_values, shape, name=name)
            result.append(
                ScalarField3D(
                    name=name,
                    label=name.replace("-", " ").title(),
                    kind="orbital",
                    values=values,
                    origin=origin,
                    axes=axes,
                    isovalues=isovalues,
                    opacity=opacity,
                    units="bohr^-3/2",
                    metadata={"source": "custom-coefficients", "column": column},
                )
            )
        return result

    if selector is None:
        return []
    spin_key = str(orbital_spin).lower()
    if len(coefficients) == 1:
        if spin_key not in {"auto", "restricted", "alpha", "both"}:
            raise ValueError("orbital_spin must be 'auto' for a restricted reference")
        spin_indices = (0,)
    else:
        if spin_key in {"auto", "both"}:
            spin_indices = (0, 1)
        elif spin_key in {"alpha", "a"}:
            spin_indices = (0,)
        elif spin_key in {"beta", "b"}:
            spin_indices = (1,)
        else:
            raise ValueError("orbital_spin must be 'auto', 'both', 'alpha', or 'beta'")

    result = []
    for spin_index in spin_indices:
        spin_name = ("alpha", "beta")[spin_index] if len(coefficients) == 2 else None
        matrix = np.asarray(coefficients[spin_index])
        if matrix.ndim != 2 or matrix.shape[0] != ao_values.shape[0]:
            raise ValueError("mo_coeff shape does not match the AO real-space dimension")
        occ = occupations[spin_index if len(occupations) == 2 else 0]
        for index, requested_label in _orbital_indices(selector, occ, matrix.shape[1]):
            base_name = f"mo-{index + 1}"
            name = f"{spin_name}-{base_name}" if spin_name else base_name
            label = f"{spin_name.title()} {requested_label}" if spin_name else requested_label
            energy = None
            if energies:
                energy_array = energies[spin_index if len(energies) == 2 else 0]
                energy = float(np.asarray(energy_array)[index])
                label += f"  E={energy:.6f} Eh"
            values = _field_values(matrix[:, index], ao_values, shape, name=name)
            result.append(
                ScalarField3D(
                    name=name,
                    label=label,
                    kind="orbital",
                    values=values,
                    origin=origin,
                    axes=axes,
                    isovalues=isovalues,
                    opacity=opacity,
                    units="bohr^-3/2",
                    metadata={
                        "orbital_index": index,
                        "spin": spin_name or "restricted",
                        "energy_hartree": energy,
                    },
                )
            )
    return result


def _default_density_matrices(reference) -> tuple[np.ndarray, ...]:
    maker = getattr(reference, "make_rdm1", None)
    if not callable(maker):
        raise TypeError("SCF object must provide make_rdm1() for density visualization")
    dm = np.asarray(maker())
    if dm.ndim == 2:
        return (dm,)
    if dm.ndim == 3 and dm.shape[0] == 2:
        return (dm[0], dm[1])
    raise ValueError("make_rdm1() must return (nao,nao) or (2,nao,nao)")


def _density_selection(reference, density) -> list[tuple[str, str, str, np.ndarray]]:
    defaults = None

    def default_matrices():
        nonlocal defaults
        if defaults is None:
            defaults = _default_density_matrices(reference)
        return defaults

    def named(key: str):
        matrices = default_matrices()
        unrestricted = len(matrices) == 2
        normalized = key.strip().lower().replace("_", "-")
        if normalized in {"electron", "total", "electron-density", "density"}:
            dm = matrices[0] if not unrestricted else matrices[0] + matrices[1]
            return ("electron-density", "Electron density", "electron-density", dm)
        if normalized in {"charge", "electronic-charge", "charge-density"}:
            dm = -(matrices[0] if not unrestricted else matrices[0] + matrices[1])
            return ("electronic-charge-density", "Electronic charge density", "difference-density", dm)
        if not unrestricted:
            raise ValueError(f"density={key!r} requires an unrestricted reference")
        if normalized in {"alpha", "alpha-density"}:
            return ("alpha-density", "Alpha density", "electron-density", matrices[0])
        if normalized in {"beta", "beta-density"}:
            return ("beta-density", "Beta density", "electron-density", matrices[1])
        if normalized in {"spin", "spin-density"}:
            return ("spin-density", "Spin density (alpha - beta)", "spin-density", matrices[0] - matrices[1])
        raise ValueError(f"unknown density selector {key!r}")

    if density is None or density is False:
        return []
    if density is True:
        return [named("electron")]
    if isinstance(density, str):
        if density.strip().lower() == "all":
            unrestricted = len(default_matrices()) == 2
            keys = ["electron", "alpha", "beta", "spin"] if unrestricted else ["electron"]
            return [named(key) for key in keys]
        return [named(density)]
    if isinstance(density, Mapping):
        result = []
        for key, matrix in density.items():
            name = str(key)
            normalized = name.lower().replace("_", "-")
            if "transition" in normalized:
                kind = "transition-density"
            elif "spin" in normalized:
                kind = "spin-density"
            else:
                kind = "difference-density"
            dm = np.asarray(matrix)
            result.append((name, name, kind, dm))
        return result
    if isinstance(density, (list, tuple)) and density and all(isinstance(item, str) for item in density):
        return [named(item) for item in density]

    array = np.asarray(density)
    if array.ndim == 2:
        return [("custom-density", "Custom density matrix", "difference-density", array)]
    if array.ndim == 3 and array.shape[0] == 2:
        alpha, beta = array
        return [
            ("electron-density", "Electron density", "electron-density", alpha + beta),
            ("alpha-density", "Alpha density", "electron-density", alpha),
            ("beta-density", "Beta density", "electron-density", beta),
            ("spin-density", "Spin density (alpha - beta)", "spin-density", alpha - beta),
        ]
    raise ValueError("density must be a selector, density matrix, spin pair, list, or mapping")


def _density_values(dm, ao_values, shape, *, name):
    dm = np.asarray(dm)
    if dm.shape != (ao_values.shape[0], ao_values.shape[0]):
        raise ValueError(
            f"density matrix {name!r} has shape {dm.shape}; expected "
            f"({ao_values.shape[0]}, {ao_values.shape[0]})"
        )
    values = np.einsum(
        "pg,pq,qg->g",
        ao_values.conj(),
        dm,
        ao_values,
        optimize=True,
    )
    return _real_array(values, name=name).reshape(shape)


def _density_fields(
    reference,
    density,
    *,
    ao_values,
    shape,
    origin,
    axes,
    isovalues,
    opacity,
) -> list[ScalarField3D]:
    result = []
    for name, label, kind, dm in _density_selection(reference, density):
        values = _density_values(dm, ao_values, shape, name=name)
        if kind == "difference-density" and np.min(values) >= -1.0e-12:
            kind = "electron-density"
        result.append(
            ScalarField3D(
                name=name,
                label=label,
                kind=kind,
                values=values,
                origin=origin,
                axes=axes,
                isovalues=isovalues,
                opacity=opacity,
                units="bohr^-3",
                metadata={"source": "density-matrix"},
            )
        )
    return result


def _total_dm(reference, supplied=None) -> np.ndarray:
    if supplied is not None and supplied is not True:
        array = np.asarray(supplied)
        if array.ndim == 3 and array.shape[0] == 2:
            return array[0] + array[1]
        if array.ndim == 2:
            return array
        raise ValueError("esp density matrix must have shape (nao,nao) or (2,nao,nao)")
    matrices = _default_density_matrices(reference)
    return matrices[0] if len(matrices) == 1 else matrices[0] + matrices[1]


def _density_requests_default_total(density) -> bool:
    if density is True:
        return True
    if isinstance(density, str):
        keys = [density]
    elif isinstance(density, (list, tuple)) and all(
        isinstance(item, str) for item in density
    ):
        keys = density
    else:
        return False
    normalized = {
        key.strip().lower().replace("_", "-")
        for key in keys
    }
    return bool(
        normalized
        & {"all", "electron", "total", "electron-density", "density"}
    )


def _nuclear_potential(molecule, points, spacing, *, regularize: bool) -> np.ndarray:
    coords = np.asarray(molecule.atom_coords(), dtype=float)
    charges_method = getattr(molecule, "atom_charges", None)
    if callable(charges_method):
        charges = np.asarray(charges_method(), dtype=float)
    else:
        charge_method = getattr(molecule, "atom_charge", None)
        if not callable(charge_method):
            raise TypeError("ESP requires atom_charges() or atom_charge(index)")
        charges = np.asarray([charge_method(i) for i in range(len(coords))], dtype=float)
    distances = np.linalg.norm(points[:, None, :] - coords[None, :, :], axis=2)
    if not regularize and np.any(distances < 1.0e-10):
        raise ValueError(
            "ESP grid contains a nucleus, where the point-charge potential diverges; "
            "use even grid dimensions or custom bounds"
        )
    cutoff = max(1.0e-10, 0.25 * float(np.min(spacing)))
    if regularize:
        distances = np.maximum(distances, cutoff)
    return np.sum(charges[None, :] / distances, axis=1)


def _pyscf_mep(reference, points, shape, spacing, dm):
    try:
        from pyscf import df, gto, lib
    except ImportError as exc:
        raise NotImplementedError("PySCF is not installed") from exc
    molecule = reference.mol
    pyscf_mol = molecule
    if not molecule.__class__.__module__.startswith("pyscf."):
        converter = getattr(molecule, "topyscf", None)
        if not callable(converter):
            raise NotImplementedError("molecule cannot be converted to PySCF")
        pyscf_mol = converter()
    density = np.asarray(dm)
    nao = int(pyscf_mol.nao_nr())
    if density.shape != (nao, nao):
        raise ValueError(
            f"density matrix shape {density.shape} does not match converted PySCF AO "
            f"dimension {nao}"
        )
    nuclear = _nuclear_potential(pyscf_mol, points, spacing, regularize=False)
    electron = np.empty(len(points), dtype=float)
    for start, stop in lib.prange(0, len(points), 600):
        fake = gto.fakemol_for_charges(points[start:stop])
        # ``fakemol_for_charges`` defaults to spherical.  Coulomb auxiliary
        # s functions are identical, but PySCF requires the representation
        # flag to match a Cartesian primary molecule.
        fake.cart = bool(getattr(pyscf_mol, "cart", False))
        integrals = df.incore.aux_e2(pyscf_mol, fake)
        electron[start:stop] = np.einsum(
            "ijp,ij->p", integrals, density, optimize=True
        ).real
    return _real_array(
        nuclear - electron,
        name="electrostatic potential",
    ).reshape(shape)


def _fft_mep(molecule, points, shape, spacing, density_values):
    try:
        from scipy.signal import fftconvolve
    except ImportError as exc:  # pragma: no cover - SciPy is a core dependency
        raise ImportError("approximate ESP visualization requires scipy") from exc
    offsets = [np.arange(-(size - 1), size, dtype=float) * step for size, step in zip(shape, spacing)]
    rx, ry, rz = np.meshgrid(*offsets, indexing="ij")
    radius = np.sqrt(rx * rx + ry * ry + rz * rz)
    kernel = np.zeros_like(radius)
    np.divide(1.0, radius, out=kernel, where=radius > 0.0)
    voxel = float(np.prod(spacing))
    electron = fftconvolve(density_values, kernel, mode="same") * voxel
    nuclear = _nuclear_potential(
        molecule,
        points,
        spacing,
        regularize=True,
    ).reshape(shape)
    return nuclear - electron


def _esp_fields(
    reference,
    esp,
    *,
    method,
    cube,
    points,
    ao_values,
    shape,
    origin,
    axes,
    density_fields,
    reuse_density_surface,
    isovalues,
    opacity,
) -> list[ScalarField3D]:
    if esp is None or esp is False:
        return []
    dm = _total_dm(reference, supplied=esp)
    density_surface = (
        next(
            (item for item in density_fields if item.name == "electron-density"),
            None,
        )
        if reuse_density_surface
        else None
    )
    additions = []
    if density_surface is None:
        surface_name = "electron-density" if not density_fields else "esp-surface-density"
        density_surface = ScalarField3D(
            name=surface_name,
            label="Electron density (ESP surface)",
            kind="electron-density",
            values=_density_values(dm, ao_values, shape, name=surface_name),
            origin=origin,
            axes=axes,
            isovalues=None,
            opacity=0.55,
            units="bohr^-3",
            metadata={"source": "density-matrix"},
        )
        additions.append(density_surface)

    method_key = str(method).lower()
    if method_key not in {"auto", "exact", "fft"}:
        raise ValueError("esp_method must be 'auto', 'exact', or 'fft'")
    exact_error = None
    if method_key in {"auto", "exact"}:
        try:
            values = _pyscf_mep(
                reference,
                points,
                shape,
                np.asarray(cube.spacing, dtype=float),
                dm,
            )
            metadata = {
                "method": "pyscf-exact",
                "approximate": False,
                "units": "hartree/e",
            }
        except Exception as exc:
            exact_error = exc
            if method_key == "exact":
                raise RuntimeError("exact PySCF ESP evaluation failed") from exc
        else:
            return additions + [
                ScalarField3D(
                    name="esp",
                    label="Electrostatic potential",
                    kind="esp",
                    values=values,
                    origin=origin,
                    axes=axes,
                    isovalues=isovalues,
                    opacity=opacity,
                    units="hartree/e",
                    surface_field=density_surface.name,
                    metadata=metadata,
                )
            ]

    values = _fft_mep(
        reference.mol,
        points,
        shape,
        np.asarray(cube.spacing, dtype=float),
        density_surface.values,
    )
    metadata = {
        "method": "fft-convolution",
        "approximate": True,
        "units": "hartree/e",
    }
    if exact_error is not None:
        # Keep the public schema deliberately stable; the exception remains
        # available through exact mode instead of being serialized to a page.
        pass
    return additions + [
        ScalarField3D(
            name="esp",
            label="Electrostatic potential (FFT approximation)",
            kind="esp",
            values=values,
            origin=origin,
            axes=axes,
            isovalues=isovalues,
            opacity=opacity,
            units="hartree/e",
            surface_field=density_surface.name,
            metadata=metadata,
        )
    ]


def _state_count(td) -> int:
    for attribute in ("e", "energies", "e_tot"):
        value = getattr(td, attribute, None)
        if value is not None:
            array = np.asarray(value)
            if array.ndim == 1 and array.size:
                return int(array.size)
    ci = getattr(td, "ci", None)
    if isinstance(ci, (list, tuple)):
        return len(ci)
    xy = getattr(td, "xy", None)
    if isinstance(xy, (list, tuple)):
        return len(xy)
    array = np.asarray(xy) if xy is not None else None
    if array is not None and array.ndim >= 2:
        return int(array.shape[-1])
    x = getattr(td, "x", None)
    if x is not None and np.asarray(x).ndim == 3:
        return int(np.asarray(x).shape[-1])
    for attribute in ("tdm", "tdm1", "transition_density_matrix", "transition_density"):
        value = getattr(td, attribute, None)
        if value is not None and not callable(value):
            array = np.asarray(value)
            if array.ndim == 3:
                return int(array.shape[0])
    raise ValueError("cannot infer the number of excited states; use an explicit state index")


def _state_indices(selector, td) -> list[int]:
    if selector is True:
        requested = [0]
    elif isinstance(selector, str):
        if selector.strip().lower() != "all":
            raise ValueError("nto must be a state index, list of indices, or 'all'")
        requested = list(range(_state_count(td)))
    elif np.isscalar(selector):
        requested = [int(selector)]
    else:
        requested = [int(value) for value in selector]
    if not requested:
        raise ValueError("NTO state list cannot be empty")
    if any(index < 0 for index in requested):
        raise IndexError("NTO state indices must be non-negative")
    count = None
    try:
        count = _state_count(td)
    except ValueError:
        pass
    if count is not None and any(index >= count for index in requested):
        raise IndexError(f"NTO state index is outside [0, {count})")
    return requested


def _xy_item(td, state, nocc, nvir) -> tuple[np.ndarray, np.ndarray]:
    dimension = nocc * nvir
    ci = getattr(td, "ci", None)
    converter = getattr(td, "vec_to_amplitudes", None)
    if isinstance(ci, (list, tuple)) and callable(converter):
        return np.asarray(converter(ci[state])), np.zeros((nocc, nvir))

    x_attr = getattr(td, "x", getattr(td, "X", None))
    if x_attr is not None:
        x = np.asarray(x_attr)
        if x.shape[:2] == (nocc, nvir) and x.ndim == 3:
            return x[:, :, state], np.zeros((nocc, nvir))
        if x.shape == (nocc, nvir):
            if state != 0:
                raise IndexError("only one transition amplitude is available")
            return x, np.zeros_like(x)

    xy = getattr(td, "xy", None)
    if isinstance(xy, (list, tuple)):
        item = xy[state]
        if isinstance(item, (list, tuple)) and len(item) == 2:
            x, y = item
            x = np.asarray(x)
            y = np.zeros_like(x) if np.isscalar(y) else np.asarray(y)
            return x.reshape(nocc, nvir), y.reshape(nocc, nvir)
        return np.asarray(item).reshape(nocc, nvir), np.zeros((nocc, nvir))
    if xy is not None:
        array = np.asarray(xy)
        if td.__class__.__module__ == "pyqed.qchem.tdscf.tdhf":
            raise NotImplementedError(
                "legacy native TDHF stores Casida eigenvectors rather than physical "
                "X/Y amplitudes; automatic NTO extraction is unavailable for this object"
            )
        if array.ndim == 2 and array.shape[0] == dimension:
            return array[:, state].reshape(nocc, nvir), np.zeros((nocc, nvir))
        if array.ndim == 2 and array.shape[0] == 2 * dimension:
            vector = array[:, state]
            return (
                vector[:dimension].reshape(nocc, nvir),
                vector[dimension:].reshape(nocc, nvir),
            )
        if array.shape == (nocc, nvir):
            return array, np.zeros_like(array)

    amplitudes = getattr(td, "amplitudes", None)
    if amplitudes is not None:
        array = np.asarray(amplitudes)
        item = array[state] if array.ndim == 3 else array
        return item.reshape(nocc, nvir), np.zeros((nocc, nvir))

    tdm = next(
        (
            candidate
            for candidate in (
                getattr(td, "tdm", None),
                getattr(td, "transition_density_matrix", None),
                getattr(td, "transition_density", None),
                getattr(td, "get_tdm", None),
            )
            if callable(candidate)
        ),
        None,
    )
    if tdm is not None:
        try:
            value = tdm(state, representation="mo")
        except TypeError:
            try:
                value = tdm(state)
            except TypeError:
                try:
                    value = tdm(state + 1, 0)
                except TypeError:
                    if state != 0:
                        raise
                    value = tdm()
        array = np.asarray(value)
        if array.shape == (nocc, nvir):
            return array, np.zeros_like(array)
        if array.ndim == 2 and array.shape[0] >= nocc and array.shape[1] >= nocc + nvir:
            return array[:nocc, nocc:nocc + nvir], np.zeros((nocc, nvir))
    for attribute in ("tdm", "tdm1", "transition_density_matrix", "transition_density"):
        value = getattr(td, attribute, None)
        if value is None or callable(value):
            continue
        array = np.asarray(value)
        if array.ndim == 3:
            array = array[state]
        elif state != 0:
            continue
        if array.shape == (nocc, nvir):
            return array, np.zeros_like(array)
        if array.ndim == 2 and array.shape[0] >= nocc and array.shape[1] >= nocc + nvir:
            return array[:nocc, nocc:nocc + nvir], np.zeros((nocc, nvir))
    raise TypeError("TD object exposes neither usable amplitudes nor a transition density matrix")


def _nto_fields(
    td,
    selector,
    *,
    reference,
    pairs,
    method,
    ao_values,
    shape,
    origin,
    axes,
    isovalues,
    opacity,
) -> list[ScalarField3D]:
    coeffs = _spin_arrays(reference, "mo_coeff")
    occs = _spin_arrays(reference, "mo_occ")
    if len(coeffs) != 1 or len(occs) != 1:
        raise NotImplementedError("automatic NTO extraction currently requires a restricted reference")
    mo_coeff = np.asarray(coeffs[0])
    mo_occ = np.asarray(occs[0])
    occ_idx = np.flatnonzero(mo_occ > 1.0e-8)
    vir_idx = np.flatnonzero(mo_occ <= 1.0e-8)
    if not len(occ_idx) or not len(vir_idx):
        raise ValueError("NTOs require occupied and virtual orbitals")
    npairs = int(pairs)
    if npairs < 1:
        raise ValueError("nto_pairs must be positive")
    method_key = str(method).lower()
    if method_key not in {"x", "transition"}:
        raise ValueError("nto_method must be 'x' or 'transition'")

    result = []
    for state in _state_indices(selector, td):
        x, y = _xy_item(td, state, len(occ_idx), len(vir_idx))
        if x.shape != (len(occ_idx), len(vir_idx)) or y.shape != x.shape:
            raise ValueError("transition amplitudes do not match occupied/virtual dimensions")
        amplitude = x if method_key == "x" else x + y
        hole_rotation, singular_values, particle_h = np.linalg.svd(amplitude, full_matrices=False)
        total = float(np.sum(singular_values**2))
        if total <= np.finfo(float).eps:
            raise ValueError(f"state {state} has a zero transition amplitude")
        particle_rotation = particle_h.conj().T
        for pair in range(min(npairs, len(singular_values))):
            weight = float(singular_values[pair] ** 2 / total)
            hole_coeff = mo_coeff[:, occ_idx] @ hole_rotation[:, pair]
            particle_coeff = mo_coeff[:, vir_idx] @ particle_rotation[:, pair]
            prefix = f"state-{state + 1}-nto-{pair + 1}"
            common = {
                "state_index": state,
                "pair_index": pair,
                "weight": weight,
                "method": method_key,
            }
            result.extend(
                [
                    ScalarField3D(
                        name=f"{prefix}-hole",
                        label=f"State {state + 1} NTO {pair + 1} hole ({weight:.1%})",
                        kind="orbital",
                        values=_field_values(hole_coeff, ao_values, shape, name="NTO hole"),
                        origin=origin,
                        axes=axes,
                        isovalues=isovalues,
                        opacity=opacity,
                        units="bohr^-3/2",
                        metadata={**common, "role": "hole"},
                    ),
                    ScalarField3D(
                        name=f"{prefix}-particle",
                        label=f"State {state + 1} NTO {pair + 1} particle ({weight:.1%})",
                        kind="orbital",
                        values=_field_values(particle_coeff, ao_values, shape, name="NTO particle"),
                        origin=origin,
                        axes=axes,
                        isovalues=isovalues,
                        opacity=opacity,
                        units="bohr^-3/2",
                        metadata={**common, "role": "particle"},
                    ),
                ]
            )
    return result


_ELEMENT_SYMBOLS = (
    "X", "H", "He", "Li", "Be", "B", "C", "N", "O", "F", "Ne", "Na",
    "Mg", "Al", "Si", "P", "S", "Cl", "Ar", "K", "Ca", "Sc", "Ti", "V",
    "Cr", "Mn", "Fe", "Co", "Ni", "Cu", "Zn", "Ga", "Ge", "As", "Se", "Br",
    "Kr", "Rb", "Sr", "Y", "Zr", "Nb", "Mo", "Tc", "Ru", "Rh", "Pd", "Ag",
    "Cd", "In", "Sn", "Sb", "Te", "I", "Xe", "Cs", "Ba", "La", "Ce", "Pr",
    "Nd", "Pm", "Sm", "Eu", "Gd", "Tb", "Dy", "Ho", "Er", "Tm", "Yb", "Lu",
    "Hf", "Ta", "W", "Re", "Os", "Ir", "Pt", "Au", "Hg", "Tl", "Pb", "Bi",
    "Po", "At", "Rn", "Fr", "Ra", "Ac", "Th", "Pa", "U", "Np", "Pu", "Am",
    "Cm", "Bk", "Cf", "Es", "Fm", "Md", "No", "Lr", "Rf", "Db", "Sg", "Bh",
    "Hs", "Mt", "Ds", "Rg", "Cn", "Nh", "Fl", "Mc", "Lv", "Ts", "Og",
)
_ELEMENT_SET = frozenset(_ELEMENT_SYMBOLS[1:])


def _safe_field_name(value: str, fallback: str) -> str:
    cleaned = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return (cleaned or fallback)[:80]


def _read_cube(path: Path, *, dataset: int | str = 0):
    """Read the core Gaussian-cube subset without requiring optional ASE."""
    if path.stat().st_size > _MAX_CUBE_BYTES:
        raise ValueError(
            f"cube file is larger than the {_MAX_CUBE_BYTES:,}-byte input limit"
        )
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except UnicodeDecodeError as exc:
        raise ValueError(f"cube file {path} is not UTF-8 text") from exc
    if len(lines) < 6:
        raise ValueError("cube file is too short")
    comment = lines[0].strip() or path.stem
    description = " ".join(line.strip() for line in lines[:2] if line.strip())
    atom_line = lines[2].split()
    if len(atom_line) < 4:
        raise ValueError("invalid cube origin line")
    signed_natoms = int(atom_line[0])
    natoms = abs(signed_natoms)
    origin = np.asarray([float(value.replace("D", "E")) for value in atom_line[1:4]])
    nval = int(atom_line[4]) if len(atom_line) >= 5 else 1
    shapes = []
    axes = []
    count_signs = []
    for line in lines[3:6]:
        values = line.split()
        if len(values) < 4:
            raise ValueError("invalid cube axis line")
        count = int(values[0])
        count_signs.append(np.sign(count))
        shapes.append(abs(count))
        axes.append([float(value.replace("D", "E")) for value in values[1:4]])
    if any(size < 2 for size in shapes):
        raise ValueError("cube grid dimensions must each be at least 2")
    if any(sign == 0 for sign in count_signs) or len(set(count_signs)) != 1:
        raise ValueError("cube grid counts must be consistently positive or negative")
    # Gaussian's convention is positive counts in Bohr and negative in Angstrom.
    length_scale = au2angstrom if count_signs[0] > 0 else 1.0
    origin *= length_scale
    axes = np.asarray(axes, dtype=float) * length_scale

    cursor = 6
    numbers = []
    positions = []
    for _ in range(natoms):
        values = lines[cursor].split()
        cursor += 1
        if len(values) < 5:
            raise ValueError("invalid cube atom line")
        numbers.append(int(float(values[0])))
        positions.append([float(value.replace("D", "E")) * length_scale for value in values[2:5]])
    if signed_natoms < 0:
        labels = []
        while cursor < len(lines) and not labels:
            row = lines[cursor].split()
            cursor += 1
            if row:
                count = int(row[0])
                labels.extend(row[1:])
                while len(labels) < count and cursor < len(lines):
                    labels.extend(lines[cursor].split())
                    cursor += 1
                labels = labels[:count]
        if labels:
            nval = len(labels)
    if isinstance(dataset, str):
        if dataset.strip().lower() != "all":
            raise ValueError("cube dataset must be an integer index or 'all'")
        selected = list(range(nval))
    else:
        index = int(dataset)
        if index != dataset:
            raise TypeError("cube dataset indices must be integers")
        if index < 0 or index >= nval:
            raise IndexError(f"cube dataset {index} is outside [0, {nval})")
        selected = [index]
    raw = []
    for line in lines[cursor:]:
        raw.extend(float(value.replace("D", "E")) for value in line.split())
    expected = int(np.prod(shapes)) * nval
    if len(raw) != expected:
        raise ValueError(f"cube contains {len(raw)} values; expected {expected}")
    array = np.asarray(raw, dtype=float).reshape((-1, nval), order="C")
    symbols = [
        _ELEMENT_SYMBOLS[number] if 0 < number < len(_ELEMENT_SYMBOLS) else "X"
        for number in numbers
    ]
    if any(symbol == "X" for symbol in symbols):
        raise ValueError("cube contains an unsupported atomic number")
    xyz = _xyz_from_arrays(symbols, np.asarray(positions, dtype=float))
    lowered = description.lower()
    if nval > 1 or "orbital" in lowered:
        kind = "orbital"
    elif "spin" in lowered:
        kind = "spin-density"
    elif "electrostatic" in lowered or "potential" in lowered or "mep" in lowered:
        kind = "esp"
    elif "density" in lowered:
        kind = "electron-density"
    else:
        kind = "generic"
    fields = []
    for index in selected:
        dataset_label = labels[index] if signed_natoms < 0 and labels else str(index + 1)
        name = _safe_field_name(
            path.stem if nval == 1 else f"{path.stem}-{dataset_label}",
            f"cube-field-{index + 1}",
        )
        label = comment if nval == 1 else f"Orbital {dataset_label}"
        fields.append(
            ScalarField3D(
                name=name,
                label=label[:120],
                kind=kind,
                values=array[:, index].reshape(tuple(shapes), order="C"),
                origin=origin,
                axes=axes,
                units=None,
                metadata={"source": "cube", "dataset": index},
            )
        )
    return xyz, tuple(fields)


def view(
    obj,
    *,
    mode: int | None = None,
    amplitude: str | float = "auto",
    frames: int = 24,
    interval: int = 30,
    orbital=None,
    coeff=None,
    orbital_spin: str = "auto",
    density=None,
    esp=False,
    esp_method: str = "auto",
    nto=None,
    nto_pairs: int = 1,
    nto_method: str = "x",
    fields: ScalarField3D | Iterable[ScalarField3D] | None = None,
    active_field: str | int | None = None,
    dataset: int | str = 0,
    nx: int = 40,
    ny: int | None = None,
    nz: int | None = None,
    margin: float = 3.0,
    bounds=None,
    isovalues=None,
    opacity: float = 0.72,
    title: str | None = None,
    representation: str = "ball-stick",
    labels: bool = False,
    width: int = 900,
    height: int = 640,
    coordinates_unit: str = "bohr",
    open_browser: bool | None = None,
) -> SceneView:
    """Build an interactive molecular/volumetric scene.

    Examples
    --------
    ``view(mol)`` shows geometry and ``view(hessian, mode=0)`` animates one
    harmonic normal mode.  For a converged SCF object, use
    ``view(mf, orbital=['homo', 'lumo'])``, ``orbital='all'``,
    ``density='all'`` (including unrestricted spin density), or ``esp=True``.
    ``view(td, nto='all')`` builds NTO hole/particle layers for every exposed
    excited-state amplitude.  A Gaussian cube path is accepted directly.

    Coordinates in generated grids are sampled in Bohr and transported to the
    browser in Angstrom.  Scalar values retain their documented atomic units.
    Volumetric data is never encoded in a URL fragment.
    """
    esp_requested = esp is not None and esp is not False
    density_requested = density is not None and density is not False
    nto_requested = nto is not None and nto is not False
    mode_requested = mode is not None
    if mode_requested and (
        orbital is not None
        or coeff is not None
        or density_requested
        or nto_requested
        or fields is not None
        or esp_requested
    ):
        raise ValueError("normal-mode animation cannot be combined with scalar fields")
    if isinstance(obj, SceneView):
        if (
            mode_requested
            or amplitude != "auto"
            or orbital is not None
            or coeff is not None
            or density_requested
            or nto_requested
            or fields is not None
            or esp_requested
        ):
            raise ValueError("cannot add computed fields when obj is already a SceneView")
        result = obj
    elif isinstance(obj, (str, Path)):
        path = Path(obj).expanduser()
        if not path.is_file():
            raise FileNotFoundError(path)
        if path.suffix.lower() not in {".cube", ".cub"}:
            raise ValueError("view(path) currently accepts .cube and .cub files")
        if (
            mode_requested
            or amplitude != "auto"
            or orbital is not None
            or coeff is not None
            or density_requested
            or nto_requested
            or fields is not None
            or esp_requested
        ):
            raise ValueError("computed field options cannot be combined with a cube path")
        xyz, cube_fields = _read_cube(path, dataset=dataset)
        result = VolumeView(
            xyz=xyz,
            fields=cube_fields,
            representation=representation,
            labels=bool(labels),
            width=width,
            height=height,
            title=title or cube_fields[0].label,
            active_field=active_field,
        )
    else:
        molecule = _molecule_from_object(obj)
        xyz = _molecule_xyz(molecule, coordinates_unit=coordinates_unit)
        vibration = None
        if mode_requested:
            vibration = _normal_mode_animation(
                obj,
                molecule,
                mode=mode,
                amplitude=amplitude,
                coordinates_unit=coordinates_unit,
                frames=frames,
                interval=interval,
            )
        external_fields: list[ScalarField3D] = []
        if fields is not None:
            if isinstance(fields, ScalarField3D):
                external_fields = [fields]
            else:
                external_fields = list(fields)

        needs_computed = (
            orbital is not None
            or coeff is not None
            or density_requested
            or nto_requested
            or esp_requested
        )
        computed: list[ScalarField3D] = []
        if needs_computed:
            reference = _scf_reference(obj)
            if reference is None:
                raise TypeError("orbital, density, ESP, and NTO views require an SCF reference")
            cube = _grid(
                molecule,
                nx=nx,
                ny=ny,
                nz=nz,
                margin=margin,
                bounds=bounds,
            )
            points, origin, axes = _grid_geometry(cube)
            shape = (cube.nx, cube.ny, cube.nz)
            ao_values = _evaluate_ao(reference, points)
            computed.extend(
                _orbital_fields(
                    reference,
                    orbital,
                    coeff=coeff,
                    orbital_spin=orbital_spin,
                    ao_values=ao_values,
                    shape=shape,
                    origin=origin,
                    axes=axes,
                    isovalues=isovalues,
                    opacity=opacity,
                )
            )
            density_result = _density_fields(
                reference,
                density,
                ao_values=ao_values,
                shape=shape,
                origin=origin,
                axes=axes,
                isovalues=isovalues,
                opacity=opacity,
            )
            computed.extend(density_result)
            computed.extend(
                _esp_fields(
                    reference,
                    esp,
                    method=esp_method,
                    cube=cube,
                    points=points,
                    ao_values=ao_values,
                    shape=shape,
                    origin=origin,
                    axes=axes,
                    density_fields=density_result,
                    reuse_density_surface=(
                        esp is True and _density_requests_default_total(density)
                    ),
                    isovalues=isovalues,
                    opacity=opacity,
                )
            )
            if nto_requested:
                computed.extend(
                    _nto_fields(
                        obj,
                        nto,
                        reference=reference,
                        pairs=nto_pairs,
                        method=nto_method,
                        ao_values=ao_values,
                        shape=shape,
                        origin=origin,
                        axes=axes,
                        isovalues=isovalues,
                        opacity=opacity,
                    )
                )

        all_fields = tuple(external_fields + computed)
        cls = VolumeView if all_fields else SceneView
        result = cls(
            xyz=xyz,
            fields=all_fields,
            representation=representation,
            labels=bool(labels),
            width=width,
            height=height,
            title=title or (vibration.label if vibration is not None else None),
            active_field=active_field,
            vibration=vibration,
        )

    should_open = not _in_notebook() if open_browser is None else bool(open_browser)
    if should_open:
        result.open()
    return result


__all__ = ["MoleculeView", "ScalarField3D", "SceneView", "VolumeView", "view"]
